Repository AY2425S2-CS2103-F15-2/tp, pull requests merged in 2025-04, with the labels that each got.

#128 Update minimum Window size and Tag Limitations
  docs/UserGuide.md
  docs/team/benny.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#164 Add Payment Sequence Diagram for Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/PaymentSequenceDiagram.puml
Labels: type.Task

#171 Update User Stories and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/UntagSequenceDiagram.puml
  docs/images/SortSequenceDiagram.png
  docs/images/UntagSequenceDiagram.png
  docs/team/danial.md
Labels: type.Task

#177 Update instructions for manual testing in DeveloperGuide
  docs/DeveloperGuide.md
Labels: type.Task

#181 Update user guide to reflect known bug when editing tags.
  docs/UserGuide.md
Labels: severity.Low, alpha-bug

#180 Add sequence diagram for `purge` command
  docs/DeveloperGuide.md
  docs/diagrams/PurgeSequenceDiagram.puml
  docs/images/PurgeSequenceDiagram.png
Labels: type.Task

#178 Update FilterSequence Diagram, UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PaymentSequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/FilterSequenceDiagram.png
  docs/images/PaymentSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
  src/test/java/seedu/address/model/person/ExpectedGradeTest.java
Labels: type.Enhancement

#182 Fix Alpha-Bugs related to error messages
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/PaymentCommand.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
Labels: type.Task, type.Bug, severity.Low, alpha-bug

#189 Close #140 by updating UserGuide as Known issues
  docs/UserGuide.md
  docs/images/TagsOverflow_1.png
  docs/images/TagsOverflow_2.png
Labels: type.Task

#191 Update Phone Number constraints
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task

#192 Branch minor bug fixes
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/CurrentGrade.java
  src/main/java/seedu/address/model/person/ExpectedGrade.java
Labels: type.Task, type.Bug

#193 Update DG and UML DG
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PurgeSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PurgeSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
Labels: type.Story

#194 Update major changes to User Guide
  docs/UserGuide.md
  docs/images/findLeeYuResult.png
  docs/images/findLiRoyResult.png
  docs/images/helpMessage.png
Labels: type.Task

#195 Update User Guide
  docs/UserGuide.md
Labels: type.Task

#196 Minor fix for UML diagrams and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/PaymentSequenceDiagram.puml
  docs/diagrams/PurgeSequenceDiagram.puml
  docs/diagrams/UntagSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/PaymentSequenceDiagram.png
  docs/images/PurgeSequenceDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/UntagSequenceDiagram.png
Labels: type.Task

#197 Minor Fix to User Guide on Known Issues
  docs/SettingUp.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#198 Minor Fix to PAYMENT_STATUS in User Guide
  docs/UserGuide.md
Labels: type.Task

#199 Minor Fix to Purge sequence diagram
  docs/diagrams/PurgeSequenceDiagram.puml
  docs/images/PurgeSequenceDiagram.png
Labels: type.Task

#200 Update Benny's Portfolio Page
  docs/team/benny.md
Labels: type.Task

#201 Update Grade with Color for Non Letter Grades
  src/main/java/seedu/address/commons/util/ColorUtil.java
  src/main/java/seedu/address/model/person/CurrentGrade.java
  src/main/java/seedu/address/model/person/ExpectedGrade.java
  src/test/java/seedu/address/commons/util/ColorUtilTest.java
  src/test/java/seedu/address/model/person/CurrentGradeTest.java
  src/test/java/seedu/address/model/person/ExpectedGradeTest.java
Labels: type.Task

#202 Minor update to LightTheme.css
  src/main/resources/view/LightTheme.css
Labels: type.Task

#203 Update MainApp version
  src/main/java/seedu/address/MainApp.java
Labels: type.Task

#290 Update Payment bugs found in PE-D
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/PaymentCommand.java
  src/main/java/seedu/address/model/person/PaymentInfo.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/PaymentCommandTest.java
Labels: type.Bug

#289 Fix typos in UG
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/samuelkwik.md
Labels: type.Bug

#291 Add glossary and fix some typos in UserGuide
  docs/UserGuide.md
Labels: type.Bug

#294 Update User Guide to make target user clearer
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/theend-alr-taken.md
Labels: type.Task

#292 Update name casing and phone numbers
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FilterSequenceDiagram.png
  docs/team/daryl.md
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.High

#296 Minor Fixes before v1.6 release
  docs/UserGuide.md
Labels: type.Task

#300 Updated DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/PurgeSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/PurgeSequenceDiagram.png
Labels: type.Story
